changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot

  categories:
    - title: Breaking changes
      labels:
        - breaking-change

    - title: Security
      labels:
        - security

    - title: Features
      labels:
        - enhancement
        - feature

    - title: Fixes
      labels:
        - bug
        - fix

    - title: Documentation and packaging
      labels:
        - documentation
        - packaging

    - title: Other changes
      labels:
        - "*"
